# -*- coding: utf-8 -*-
#
# Iris - Email Sender
# Copyright (C) 2026 Marco Lombardo
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version. It is distributed WITHOUT ANY WARRANTY; see the
# GNU Affero General Public License in LICENSE for details.
#
# A commercial licence, without the AGPL obligations, is available for use in
# proprietary or closed-source products - see COMMERCIAL-LICENSE.md.
"""Tests for .github/workflows/build.yml itself.

GitHub Actions is the only thing that can actually run the workflow, so these
tests parse the YAML instead: they catch a regression in the release title or
notes locally, rather than noticing it only after a real tag is pushed and a
published release shows up with no title.
"""

import pathlib

import yaml

WORKFLOW_PATH = (
    pathlib.Path(__file__).resolve().parent.parent / ".github" / "workflows" / "build.yml"
)

RELEASE_TAG_CONDITION = "startsWith(github.ref, 'refs/tags/v')"


def load_workflow():
    return yaml.safe_load(WORKFLOW_PATH.read_text(encoding="utf-8"))


def build_job_steps():
    return load_workflow()["jobs"]["build-windows"]["steps"]


def find_release_step(steps):
    return next(
        (step for step in steps if step.get("uses", "").startswith("softprops/action-gh-release")),
        None,
    )


def find_title_fallback_step(steps, after_index):
    return next(
        (
            step
            for step in steps[after_index + 1 :]
            if "gh release edit" in step.get("run", "")
        ),
        None,
    )


def test_workflow_file_parses_and_has_the_build_job():
    workflow = load_workflow()
    assert "build-windows" in workflow["jobs"]


def test_the_release_step_sets_a_fixed_readable_title():
    """Regression: a release published with no ``name:`` shows up with a
    blank title in the GitHub UI — only the tag name is shown as a fallback.
    """
    step = find_release_step(build_job_steps())
    assert step is not None, "no softprops/action-gh-release step found"
    title = step.get("with", {}).get("name", "")
    assert title.strip(), "release title (with.name) must not be empty"
    assert "Iris" in title


def test_the_release_step_sets_fixed_notes_not_generated_ones():
    """Regression: without ``body:`` the notes are left empty; using
    ``generate_release_notes: true`` instead would replace them with a raw
    commit-log dump.
    """
    step = find_release_step(build_job_steps())
    assert step is not None
    with_block = step.get("with", {})
    assert with_block.get("body", "").strip(), "release notes (with.body) must not be empty"
    assert not with_block.get("generate_release_notes"), (
        "generate_release_notes would override the fixed notes with an autogenerated log"
    )


def test_a_fallback_step_forces_the_title_on_an_already_published_release():
    """Regression: a release created before this step existed — or edited by
    hand — can keep a stale title. softprops updates an existing release,
    but a ``gh release edit`` must still run unconditionally after it so a
    re-run always corrects the title and notes, whatever they currently are.
    """
    steps = build_job_steps()
    release_index = next(
        index
        for index, step in enumerate(steps)
        if step.get("uses", "").startswith("softprops/action-gh-release")
    )
    fallback = find_title_fallback_step(steps, release_index)
    assert fallback is not None, "no `gh release edit` fallback step after the release step"
    assert "--title" in fallback["run"]
    assert "--notes" in fallback["run"]


def test_the_release_steps_only_run_on_version_tags():
    """A build triggered by workflow_dispatch on a branch must not touch the
    release — only a push of a ``v*`` tag (or a dispatch against one) should.
    """
    release_or_fallback = [
        step
        for step in build_job_steps()
        if step.get("uses", "").startswith("softprops/action-gh-release")
        or "gh release edit" in step.get("run", "")
    ]
    assert release_or_fallback, "expected at least the release step and its fallback"
    for step in release_or_fallback:
        assert step.get("if") == RELEASE_TAG_CONDITION
